language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get install libjansson-dev
 - git clean -x -f
 - ./autogen.sh
script:
 - ./configure
 - make -j8
 - make check
notifications:
    email: false
